#!/bin/bash
rm -rf Day*;
for i in {1..25}; do 
name=Day$i;
echo $name;
(mkdir $name && cd $name && swift package init --type executable && swift package generate-xcodeproj && ln -s $(PWD)/../Shared/Sources/Shared.swift Sources/Shared.swift)
done